import json
from pathlib import Path

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🏆 Amazon ML Challenge 2026: Business Entity Resolution\n",
    "## Group-Wise LightGBM LambdaRank Pipeline (`code_1/rank_pipeline.py`)\n",
    "\n",
    "This Kaggle notebook implements a high-performance, self-contained **Group-Wise Learning-to-Rank (LambdaRank)** pipeline for **Business Entity Resolution**.\n",
    "\n",
    "---\n",
    "\n",
    "### 📌 Pipeline Architecture & Key Highlights\n",
    "1. **Multilingual & Geographic Text Normalization**:\n",
    "   - Strips Latin accents/diacritics while preserving Indic scripts (**Devanagari, Tamil, Kannada**).\n",
    "   - Standardizes legal entity suffixes (Pvt Ltd, LLC, S.A.R.L., etc.).\n",
    "   - Extracts postal PIN codes (India 6-digit, US/France 5-digit) and house/plot numbers.\n",
    "2. **Inverted Index Multi-Key Union Blocking**:\n",
    "   - 8 distinct blocking strategies (**B1-B8**) targeting exact clean name, token prefixes, PIN codes, numeric tokens, door/locality combos, locality landmarks, and subword 3-grams.\n",
    "   - Compact `uint32` postings lists (`array('I')`) ensuring low RAM usage (<1.5 GB).\n",
    "3. **32-Dimensional RapidFuzz Pairwise Feature Vector**:\n",
    "   - C++ accelerated string metrics (Ratio, Partial Ratio, Token Sort, Token Set, WRatio, Jaro-Winkler, Word Jaccard).\n",
    "   - Subword character n-gram overlaps (3-grams, 4-grams).\n",
    "   - Structured door/plot number disagreement and non-linear name-address interaction signals.\n",
    "4. **Group-Wise Query Ranking (`LGBMRanker` - LambdaRank)**:\n",
    "   - Unlike standard pairwise binary classification, candidate pairs are grouped per `source1` entity (`query group`).\n",
    "   - Model learns relative candidate ordering to rank true entity matches above hard negative candidates.\n",
    "5. **Dynamic Macro F0.5 Threshold Optimization**:\n",
    "   - Quantile grid search on held-out validation query groups to find decision threshold $\\tau$ maximizing official Macro F0.5 metric.\n",
    "6. **Country-Partitioned Streaming Inference**:\n",
    "   - Partitioned execution by country (India, US, France, etc.) to generate `matching_results.tsv` and `candidate_pairs.tsv` with ultra-low memory footprint.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ensure required libraries are installed\n",
    "import sys\n",
    "import subprocess\n",
    "\n",
    "def install_if_missing(package):\n",
    "    try:\n",
    "        __import__(package)\n",
    "    except ImportError:\n",
    "        print(f\"Installing {package}...\")\n",
    "        subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", package, \"-q\"])\n",
    "\n",
    "install_if_missing(\"rapidfuzz\")\n",
    "install_if_missing(\"lightgbm\")\n",
    "install_if_missing(\"scikit-learn\")\n",
    "install_if_missing(\"tqdm\")\n",
    "install_if_missing(\"pandas\")\n",
    "install_if_missing(\"numpy\")\n",
    "\n",
    "import os\n",
    "import re\n",
    "import gc\n",
    "import csv\n",
    "import random\n",
    "import unicodedata\n",
    "from array import array\n",
    "from pathlib import Path\n",
    "from typing import Dict, List, Set, Tuple, Optional, Any\n",
    "from collections import defaultdict\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from rapidfuzz import fuzz, distance\n",
    "from lightgbm import LGBMRanker, early_stopping, log_evaluation\n",
    "from tqdm.auto import tqdm\n",
    "\n",
    "print(\"✅ Environment ready and libraries loaded!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Automatic Kaggle & Local Dataset Path Resolver\n",
    "def locate_dataset_files():\n",
    "    \"\"\"Dynamically find dataset files across Kaggle input directories and local paths.\"\"\"\n",
    "    possible_roots = [\n",
    "        Path(\"/kaggle/input/test-data\"),\n",
    "        Path(\"/kaggle/input/test_data\"),\n",
    "        Path(\"/kaggle/input/training-data\"),\n",
    "        Path(\"/kaggle/input/training_data\"),\n",
    "        Path(\"/kaggle/input/amazon-ml-challenge-2026\"),\n",
    "        Path(\"/kaggle/input\"),\n",
    "        Path(\"./student_resource/dataset\"),\n",
    "        Path(\"./dataset\"),\n",
    "        Path(\"../student_resource/dataset\"),\n",
    "        Path(\"../dataset\"),\n",
    "        Path(\".\"),\n",
    "    ]\n",
    "    \n",
    "    train_s1 = train_s2 = train_s3 = train_gt = None\n",
    "    test_s1 = test_s2 = test_s3 = None\n",
    "    \n",
    "    # Recursive search under candidate root paths\n",
    "    for root in possible_roots:\n",
    "        if not root.exists():\n",
    "            continue\n",
    "        for path in root.rglob(\"*.tsv\"):\n",
    "            name = path.name.lower()\n",
    "            if name == \"train_source1.tsv\" and not train_s1: train_s1 = path\n",
    "            elif name == \"train_source2.tsv\" and not train_s2: train_s2 = path\n",
    "            elif name == \"train_source3.tsv\" and not train_s3: train_s3 = path\n",
    "            elif name == \"train_ground_truth.tsv\" and not train_gt: train_gt = path\n",
    "            elif name == \"test_source1.tsv\" and not test_s1: test_s1 = path\n",
    "            elif name == \"test_source2.tsv\" and not test_s2: test_s2 = path\n",
    "            elif name == \"test_source3.tsv\" and not test_s3: test_s3 = path\n",
    "            \n",
    "    paths = {\n",
    "        \"TRAIN_SOURCE1\": train_s1,\n",
    "        \"TRAIN_SOURCE2\": train_s2,\n",
    "        \"TRAIN_SOURCE3\": train_s3,\n",
    "        \"TRAIN_GROUND_TRUTH\": train_gt,\n",
    "        \"TEST_SOURCE1\": test_s1,\n",
    "        \"TEST_SOURCE2\": test_s2,\n",
    "        \"TEST_SOURCE3\": test_s3,\n",
    "    }\n",
    "    \n",
    "    print(\"📂 Resolved Dataset Paths:\")\n",
    "    all_found = True\n",
    "    for k, v in paths.items():\n",
    "        status = \"✅ FOUND\" if v and v.exists() else \"❌ MISSING\"\n",
    "        print(f\"  {k:20s}: {v} ({status})\")\n",
    "        if not v or not v.exists():\n",
    "            all_found = False\n",
    "            \n",
    "    if not all_found:\n",
    "        print(\"⚠️ Warning: Some dataset files were not found under expected paths!\")\n",
    "    return paths\n",
    "\n",
    "DATA_PATHS = locate_dataset_files()\n",
    "\n",
    "# Determine Output Directory\n",
    "if Path(\"/kaggle/working\").exists():\n",
    "    OUTPUT_DIR = Path(\"/kaggle/working\")\n",
    "else:\n",
    "    OUTPUT_DIR = Path(\"./output\")\n",
    "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "MATCHING_RESULTS_PATH = OUTPUT_DIR / \"matching_results.tsv\"\n",
    "CANDIDATE_PAIRS_PATH = OUTPUT_DIR / \"candidate_pairs.tsv\"\n",
    "print(f\"📌 Output Files:\\n  Matching: {MATCHING_RESULTS_PATH}\\n  Candidates: {CANDIDATE_PAIRS_PATH}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Text & Geographic Normalization Module\n",
    "def is_empty_or_nan(val: Any) -> bool:\n",
    "    if val is None:\n",
    "        return True\n",
    "    if not isinstance(val, str):\n",
    "        try:\n",
    "            if pd.isna(val):\n",
    "                return True\n",
    "        except Exception:\n",
    "            pass\n",
    "    s = str(val).strip()\n",
    "    return not s or s.lower() in (\"nan\", \"none\", \"null\")\n",
    "\n",
    "def strip_accents(text: str) -> str:\n",
    "    if is_empty_or_nan(text):\n",
    "        return \"\"\n",
    "    res = []\n",
    "    for ch in str(text):\n",
    "        if ('\\u00c0' <= ch <= '\\u024f') or ('\\u1e00' <= ch <= '\\u1eff'):\n",
    "            decomp = unicodedata.normalize(\"NFKD\", ch)\n",
    "            res.append(\"\".join(c for c in decomp if unicodedata.category(c) != \"Mn\"))\n",
    "        else:\n",
    "            res.append(ch)\n",
    "    return \"\".join(res)\n",
    "\n",
    "def clean_punctuation_and_symbols(text: str) -> str:\n",
    "    if is_empty_or_nan(text):\n",
    "        return \"\"\n",
    "    res = []\n",
    "    for c in text:\n",
    "        cat = unicodedata.category(c)\n",
    "        if cat.startswith(('P', 'S')) and c not in ('-', '_'):\n",
    "            res.append(' ')\n",
    "        else:\n",
    "            res.append(c)\n",
    "    return \"\".join(res)\n",
    "\n",
    "LEGAL_SUFFIXES = {\n",
    "    r'\\bprivate limited\\b': 'pvt ltd',\n",
    "    r'\\bpvt ltd\\b': 'pvt ltd',\n",
    "    r'\\bpvt\\.\\s*ltd\\.\\b': 'pvt ltd',\n",
    "    r'\\blimited\\b': 'ltd',\n",
    "    r'\\bltd\\.\\b': 'ltd',\n",
    "    r'\\bcorporation\\b': 'corp',\n",
    "    r'\\binc\\.\\b': 'inc',\n",
    "    r'\\bincorporated\\b': 'inc',\n",
    "    r'\\bcompany\\b': 'co',\n",
    "    r'\\bllc\\b': 'llc',\n",
    "    r'\\bllp\\b': 'llp',\n",
    "    r'\\bgmbh\\b': 'gmbh',\n",
    "    r'\\bs\\.a\\.r\\.l\\.\\b': 'sarl',\n",
    "    r'\\bsarl\\b': 'sarl',\n",
    "    r'\\bsa\\b': 'sa',\n",
    "}\n",
    "\n",
    "STOPWORDS = {'and', 'the', 'of', 'in', 'for', 'co', '&', 'm/s', 'messrs'}\n",
    "\n",
    "def normalize_name(name: Any) -> str:\n",
    "    if is_empty_or_nan(name):\n",
    "        return \"\"\n",
    "    s = strip_accents(str(name)).lower()\n",
    "    s = clean_punctuation_and_symbols(s)\n",
    "    for pattern, repl in LEGAL_SUFFIXES.items():\n",
    "        s = re.sub(pattern, repl, s)\n",
    "    tokens = [t for t in s.split() if t not in STOPWORDS]\n",
    "    return \" \".join(tokens)\n",
    "\n",
    "def normalize_address(address: Any) -> str:\n",
    "    if is_empty_or_nan(address):\n",
    "        return \"\"\n",
    "    s = strip_accents(str(address)).lower()\n",
    "    s = clean_punctuation_and_symbols(s)\n",
    "    abbrevs = {\n",
    "        r'\\bstreet\\b': 'st', r'\\broad\\b': 'rd', r'\\bavenue\\b': 'ave',\n",
    "        r'\\bboulevard\\b': 'blvd', r'\\bdrive\\b': 'dr', r'\\blane\\b': 'ln',\n",
    "        r'\\bbuilding\\b': 'bldg', r'\\bapartment\\b': 'apt', r'\\bsuite\\b': 'ste',\n",
    "        r'\\bfloor\\b': 'fl', r'\\bplot\\b': 'plt', r'\\bsector\\b': 'sec',\n",
    "        r'\\bnagar\\b': 'ngr', r'\\bmarg\\b': 'mg'\n",
    "    }\n",
    "    for pattern, repl in abbrevs.items():\n",
    "        s = re.sub(pattern, repl, s)\n",
    "    return \" \".join(s.split())\n",
    "\n",
    "def extract_postal_code(address: Any, country: Any = \"\") -> str:\n",
    "    if is_empty_or_nan(address):\n",
    "        return \"\"\n",
    "    cntry = str(country).strip().upper() if not is_empty_or_nan(country) else \"\"\n",
    "    addr_str = str(address)\n",
    "    if cntry in (\"INDIA\", \"IN\", \"IND\") or not cntry:\n",
    "        match = re.search(r'\\b([1-9][0-9]{5})\\b', addr_str)\n",
    "        if match:\n",
    "            return match.group(1)\n",
    "    if cntry in (\"UNITED STATES\", \"US\", \"USA\", \"FRANCE\", \"FR\") or not cntry:\n",
    "        match = re.search(r'\\b([0-9]{5})(?:-[0-9]{4})?\\b', addr_str)\n",
    "        if match:\n",
    "            return match.group(1)\n",
    "    return \"\"\n",
    "\n",
    "def extract_numeric_tokens(address: Any) -> set:\n",
    "    if is_empty_or_nan(address):\n",
    "        return set()\n",
    "    return set(re.findall(r'\\b\\d+\\b', str(address)))\n",
    "\n",
    "COUNTRY_MAP = {\n",
    "    'in': 'INDIA', 'ind': 'INDIA', 'india': 'INDIA',\n",
    "    'us': 'UNITED STATES', 'usa': 'UNITED STATES', 'united states': 'UNITED STATES',\n",
    "    'fr': 'FRANCE', 'fra': 'FRANCE', 'france': 'FRANCE'\n",
    "}\n",
    "\n",
    "def normalize_country(country: Any) -> str:\n",
    "    if is_empty_or_nan(country):\n",
    "        return \"UNKNOWN\"\n",
    "    c = str(country).strip().lower()\n",
    "    return COUNTRY_MAP.get(c, c.upper())\n",
    "\n",
    "print(\"✅ Normalization utilities loaded!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Inverted Index Multi-Key Union Blocker\n",
    "class MultiKeyBlocker:\n",
    "    \"\"\"\n",
    "    Multi-Key Inverted Index Blocker with 8 blocking key strategies (B1-B8),\n",
    "    using compact uint32 postings list arrays ('I') for low RAM consumption.\n",
    "    \"\"\"\n",
    "    def __init__(self, max_candidates_per_s1: int = 100):\n",
    "        self.max_candidates = max_candidates_per_s1\n",
    "        self.index = defaultdict(lambda: array('I'))\n",
    "        self.candidate_ids = []\n",
    "        self.cand_id_to_idx = {}\n",
    "\n",
    "    def generate_blocking_keys(self, name: str, address: str, country: str) -> Set[str]:\n",
    "        keys = set()\n",
    "        norm_name = normalize_name(name)\n",
    "        norm_addr = normalize_address(address)\n",
    "        norm_cntry = normalize_country(country)\n",
    "        pin = extract_postal_code(address, country)\n",
    "        nums = extract_numeric_tokens(address)\n",
    "        \n",
    "        # B1: Clean exact name + country\n",
    "        if norm_name:\n",
    "            keys.add(f\"B1:{norm_name}|{norm_cntry}\")\n",
    "        \n",
    "        # B2: Name token prefix combo\n",
    "        tokens = norm_name.split()\n",
    "        if tokens:\n",
    "            first_tok = tokens[0]\n",
    "            if len(first_tok) >= 3:\n",
    "                keys.add(f\"B2:{first_tok[:4]}|{norm_cntry}\")\n",
    "            if len(tokens) >= 2:\n",
    "                second_tok = tokens[1]\n",
    "                keys.add(f\"B2_DUAL:{first_tok[:3]}_{second_tok[:3]}|{norm_cntry}\")\n",
    "                \n",
    "        # B3: Postal PIN code + country\n",
    "        if pin:\n",
    "            keys.add(f\"B3:{pin}|{norm_cntry}\")\n",
    "            if norm_name and len(norm_name) >= 3:\n",
    "                keys.add(f\"B3_NAME:{pin}_{norm_name[:3]}|{norm_cntry}\")\n",
    "                \n",
    "        # B4: Numeric building/street tokens + first name token\n",
    "        if nums and tokens:\n",
    "            for num in list(nums)[:2]:\n",
    "                keys.add(f\"B4:{tokens[0][:3]}_{num}|{norm_cntry}\")\n",
    "                \n",
    "        # B5: Subword character 3-grams for typo resilience\n",
    "        if norm_name and len(norm_name) >= 4:\n",
    "            clean_name_nospace = norm_name.replace(\" \", \"\")\n",
    "            for i in range(min(len(clean_name_nospace) - 2, 4)):\n",
    "                gram = clean_name_nospace[i:i+3]\n",
    "                keys.add(f\"B5:{gram}|{norm_cntry}\")\n",
    "                \n",
    "        # B6: Locality & Street token + PIN\n",
    "        addr_tokens = norm_addr.split()\n",
    "        if addr_tokens and pin:\n",
    "            for atok in addr_tokens:\n",
    "                if len(atok) >= 4 and not atok.isdigit():\n",
    "                    keys.add(f\"B6:{pin}_{atok[:4]}|{norm_cntry}\")\n",
    "                    break\n",
    "                    \n",
    "        return keys\n",
    "\n",
    "    def build_candidate_index_from_records(self, candidate_records: List[Tuple[str, str, str, str]], show_progress: bool = False):\n",
    "        iterator = tqdm(candidate_records, desc=\"Indexing Candidates\") if show_progress else candidate_records\n",
    "        for cid, name, address, country in iterator:\n",
    "            if cid in self.cand_id_to_idx:\n",
    "                continue\n",
    "            idx = len(self.candidate_ids)\n",
    "            self.candidate_ids.append(cid)\n",
    "            self.cand_id_to_idx[cid] = idx\n",
    "            \n",
    "            keys = self.generate_blocking_keys(name, address, country)\n",
    "            for key in keys:\n",
    "                self.index[key].append(idx)\n",
    "\n",
    "    def retrieve_candidates_for_record(self, s1_id: str, name: str, address: str, country: str) -> List[str]:\n",
    "        keys = self.generate_blocking_keys(name, address, country)\n",
    "        cand_counts = defaultdict(int)\n",
    "        \n",
    "        for key in keys:\n",
    "            if key in self.index:\n",
    "                postings = self.index[key]\n",
    "                if len(postings) > 2000:\n",
    "                    continue\n",
    "                for c_idx in postings:\n",
    "                    cand_counts[c_idx] += 1\n",
    "                    \n",
    "        if not cand_counts:\n",
    "            return []\n",
    "            \n",
    "        sorted_cands = sorted(cand_counts.items(), key=lambda x: x[1], reverse=True)\n",
    "        top_cands = [self.candidate_ids[c_idx] for c_idx, _ in sorted_cands[:self.max_candidates]]\n",
    "        return top_cands\n",
    "\n",
    "    def clear(self):\n",
    "        self.index.clear()\n",
    "        self.candidate_ids.clear()\n",
    "        self.cand_id_to_idx.clear()\n",
    "\n",
    "print(\"✅ MultiKeyBlocker defined!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 32-Dimensional RapidFuzz Pairwise Feature Extraction\n",
    "FEATURE_NAMES = [\n",
    "    \"name_ratio\", \"name_partial_ratio\", \"name_token_sort_ratio\", \"name_token_set_ratio\",\n",
    "    \"name_w_ratio\", \"name_jaro_winkler\", \"name_word_jaccard\", \"name_len_diff_ratio\",\n",
    "    \"name_exact_clean\", \"addr_ratio\", \"addr_partial_ratio\", \"addr_token_sort_ratio\",\n",
    "    \"addr_token_set_ratio\", \"addr_word_jaccard\", \"addr_len_diff_ratio\", \"addr_is_empty_either\",\n",
    "    \"country_exact\", \"pin_match\", \"pin_mismatch\", \"pin_missing_either\", \"pin_both_present\",\n",
    "    \"numeric_token_jaccard\", \"has_common_number\", \"is_source_2\", \"name_char3_jaccard\",\n",
    "    \"name_char4_jaccard\", \"house_num_mismatch\", \"name_addr_mult\", \"name_token_set_addr_mult\",\n",
    "    \"name_exact_pin_match\", \"strong_name_conflicting_addr\", \"pin_conflict_strong_name\"\n",
    "]\n",
    "\n",
    "def _get_char_ngrams(s: str, n: int) -> Set[str]:\n",
    "    if len(s) < n:\n",
    "        return {s} if s else set()\n",
    "    return {s[i:i+n] for i in range(len(s) - n + 1)}\n",
    "\n",
    "def compute_pair_features(\n",
    "    s1_name: str, s1_addr: str, s1_country: str,\n",
    "    cand_id: str, cand_name: str, cand_addr: str, cand_country: str,\n",
    "    s1_norm_name: Optional[str] = None, s1_norm_addr: Optional[str] = None,\n",
    "    s1_pin: Optional[str] = None, s1_nums: Optional[set] = None,\n",
    "    cand_norm_name: Optional[str] = None, cand_norm_addr: Optional[str] = None,\n",
    "    cand_pin: Optional[str] = None, cand_nums: Optional[set] = None\n",
    ") -> List[float]:\n",
    "    n1 = s1_norm_name if s1_norm_name is not None else normalize_name(s1_name)\n",
    "    n2 = cand_norm_name if cand_norm_name is not None else normalize_name(cand_name)\n",
    "    a1 = s1_norm_addr if s1_norm_addr is not None else normalize_address(s1_addr)\n",
    "    a2 = cand_norm_addr if cand_norm_addr is not None else normalize_address(cand_addr)\n",
    "    c1 = normalize_country(s1_country)\n",
    "    c2 = normalize_country(cand_country)\n",
    "    p1 = s1_pin if s1_pin is not None else extract_postal_code(s1_addr, s1_country)\n",
    "    p2 = cand_pin if cand_pin is not None else extract_postal_code(cand_addr, cand_country)\n",
    "    nums1 = s1_nums if s1_nums is not None else extract_numeric_tokens(s1_addr)\n",
    "    nums2 = cand_nums if cand_nums is not None else extract_numeric_tokens(cand_addr)\n",
    "\n",
    "    name_ratio = fuzz.ratio(n1, n2) / 100.0\n",
    "    name_partial_ratio = fuzz.partial_ratio(n1, n2) / 100.0\n",
    "    name_token_sort_ratio = fuzz.token_sort_ratio(n1, n2) / 100.0\n",
    "    name_token_set_ratio = fuzz.token_set_ratio(n1, n2) / 100.0\n",
    "    name_w_ratio = fuzz.WRatio(n1, n2) / 100.0\n",
    "    name_jaro_winkler = distance.JaroWinkler.similarity(n1, n2)\n",
    "    toks1, toks2 = set(n1.split()), set(n2.split())\n",
    "    name_word_jaccard = len(toks1 & toks2) / max(len(toks1 | toks2), 1)\n",
    "    name_len_diff = abs(len(n1) - len(n2)) / max(len(n1), len(n2), 1)\n",
    "    name_exact = 1.0 if (n1 and n1 == n2) else 0.0\n",
    "\n",
    "    addr_empty = 1.0 if (not a1 or not a2) else 0.0\n",
    "    if not addr_empty:\n",
    "        addr_ratio = fuzz.ratio(a1, a2) / 100.0\n",
    "        addr_partial_ratio = fuzz.partial_ratio(a1, a2) / 100.0\n",
    "        addr_token_sort_ratio = fuzz.token_sort_ratio(a1, a2) / 100.0\n",
    "        addr_token_set_ratio = fuzz.token_set_ratio(a1, a2) / 100.0\n",
    "        atok1, atok2 = set(a1.split()), set(a2.split())\n",
    "        addr_word_jaccard = len(atok1 & atok2) / max(len(atok1 | atok2), 1)\n",
    "        addr_len_diff = abs(len(a1) - len(a2)) / max(len(a1), len(a2), 1)\n",
    "    else:\n",
    "        addr_ratio = addr_partial_ratio = addr_token_sort_ratio = addr_token_set_ratio = addr_word_jaccard = 0.0\n",
    "        addr_len_diff = 1.0\n",
    "\n",
    "    country_exact = 1.0 if (c1 and c2 and c1 == c2) else 0.0\n",
    "    has_p1 = p1 is not None and len(p1) > 0\n",
    "    has_p2 = p2 is not None and len(p2) > 0\n",
    "    both_pins = 1.0 if (has_p1 and has_p2) else 0.0\n",
    "    pin_missing = 1.0 if (not has_p1 or not has_p2) else 0.0\n",
    "    pin_match = 1.0 if (both_pins and p1 == p2) else 0.0\n",
    "    pin_mismatch = 1.0 if (both_pins and p1 != p2) else 0.0\n",
    "\n",
    "    num_jaccard = len(nums1 & nums2) / max(len(nums1 | nums2), 1) if (nums1 and nums2) else 0.0\n",
    "    common_num = 1.0 if (nums1 and nums2 and len(nums1 & nums2) > 0) else 0.0\n",
    "    is_s2 = 1.0 if cand_id.startswith(\"S2-\") else 0.0\n",
    "\n",
    "    ng3_1, ng3_2 = _get_char_ngrams(n1, 3), _get_char_ngrams(n2, 3)\n",
    "    name_char3_jaccard = len(ng3_1 & ng3_2) / max(len(ng3_1 | ng3_2), 1) if (ng3_1 and ng3_2) else 0.0\n",
    "    ng4_1, ng4_2 = _get_char_ngrams(n1, 4), _get_char_ngrams(n2, 4)\n",
    "    name_char4_jaccard = len(ng4_1 & ng4_2) / max(len(ng4_1 | ng4_2), 1) if (ng4_1 and ng4_2) else 0.0\n",
    "\n",
    "    house_num_mismatch = 1.0 if (nums1 and nums2 and len(nums1 & nums2) == 0) else 0.0\n",
    "    name_addr_mult = name_ratio * addr_ratio\n",
    "    name_token_set_addr_mult = name_token_set_ratio * addr_token_set_ratio\n",
    "    name_exact_pin_match = name_exact * pin_match\n",
    "    strong_name_conflicting_addr = 1.0 if (name_ratio >= 0.85 and addr_ratio < 0.40 and not addr_empty) else 0.0\n",
    "    pin_conflict_strong_name = 1.0 if (pin_mismatch == 1.0 and name_ratio >= 0.80) else 0.0\n",
    "\n",
    "    return [\n",
    "        name_ratio, name_partial_ratio, name_token_sort_ratio, name_token_set_ratio,\n",
    "        name_w_ratio, name_jaro_winkler, name_word_jaccard, name_len_diff, name_exact,\n",
    "        addr_ratio, addr_partial_ratio, addr_token_sort_ratio, addr_token_set_ratio,\n",
    "        addr_word_jaccard, addr_len_diff, addr_empty, country_exact, pin_match,\n",
    "        pin_mismatch, pin_missing, both_pins, num_jaccard, common_num, is_s2,\n",
    "        name_char3_jaccard, name_char4_jaccard, house_num_mismatch, name_addr_mult,\n",
    "        name_token_set_addr_mult, name_exact_pin_match, strong_name_conflicting_addr,\n",
    "        pin_conflict_strong_name\n",
    "    ]\n",
    "\n",
    "print(\"✅ Feature engineering module loaded!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# RecordCache, Ground Truth Loading & Data Management\n",
    "Record = Tuple[str, str, str, str]\n",
    "\n",
    "class RecordCache:\n",
    "    \"\"\"Cache normalized representations of candidate records in memory.\"\"\"\n",
    "    def __init__(self, records: List[Record]):\n",
    "        self.norm_names = {}\n",
    "        self.norm_addrs = {}\n",
    "        self.pins = {}\n",
    "        self.nums = {}\n",
    "        self.countries = {}\n",
    "        for cid, name, address, country in records:\n",
    "            self.norm_names[cid] = normalize_name(name)\n",
    "            self.norm_addrs[cid] = normalize_address(address)\n",
    "            self.pins[cid] = extract_postal_code(address, country)\n",
    "            self.nums[cid] = extract_numeric_tokens(address)\n",
    "            self.countries[cid] = normalize_country(country)\n",
    "\n",
    "    def clear(self):\n",
    "        self.norm_names.clear()\n",
    "        self.norm_addrs.clear()\n",
    "        self.pins.clear()\n",
    "        self.nums.clear()\n",
    "        self.countries.clear()\n",
    "\n",
    "def read_source(path: Path):\n",
    "    with path.open(\"r\", encoding=\"utf-8\") as f:\n",
    "        next(f, None)\n",
    "        for line in f:\n",
    "            p = line.rstrip(\"\\r\\n\").split(\"\\t\")\n",
    "            if len(p) >= 4:\n",
    "                yield (p[0].strip(), p[1].strip(), p[2].strip(), p[3].strip())\n",
    "\n",
    "def load_ground_truth_map(gt_path: Path) -> Dict[str, Set[str]]:\n",
    "    gt_map = defaultdict(set)\n",
    "    with gt_path.open(\"r\", encoding=\"utf-8\") as f:\n",
    "        next(f, None)\n",
    "        for line in f:\n",
    "            parts = line.rstrip(\"\\r\\n\").split(\"\\t\")\n",
    "            if len(parts) >= 2:\n",
    "                s1 = parts[0].strip()\n",
    "                matches = set(parts[1].strip().split(\",\")) if parts[1].strip() else set()\n",
    "                gt_map[s1] = matches\n",
    "    return gt_map\n",
    "\n",
    "def get_s1_records(path: Path, wanted: Set[str]) -> List[Record]:\n",
    "    found = {}\n",
    "    for rec in read_source(path):\n",
    "        if rec[0] in wanted:\n",
    "            found[rec[0]] = rec\n",
    "            if len(found) == len(wanted):\n",
    "                break\n",
    "    return list(found.values())\n",
    "\n",
    "def collect_training_candidates(cohort: Set[str], gt: Dict[str, Set[str]], max_background: int):\n",
    "    needed = set().union(*(gt.get(sid, set()) for sid in cohort)) if cohort else set()\n",
    "    records = []\n",
    "    per_source_bg = max_background // 2\n",
    "    for path in (DATA_PATHS[\"TRAIN_SOURCE2\"], DATA_PATHS[\"TRAIN_SOURCE3\"]):\n",
    "        bg = 0\n",
    "        for rec in read_source(path):\n",
    "            if rec[0] in needed:\n",
    "                records.append(rec)\n",
    "            elif bg < per_source_bg:\n",
    "                records.append(rec)\n",
    "                bg += 1\n",
    "    return records\n",
    "\n",
    "print(\"✅ Dataset loading helper utilities ready!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Group-Wise Rank Matrix Construction & Decision Threshold Tuning\n",
    "def make_rank_matrix(\n",
    "    s1_records: List[Record], cache: RecordCache, blocker: MultiKeyBlocker,\n",
    "    gt: Dict[str, Set[str]], max_cands: int, keep_pairs: bool = False,\n",
    "):\n",
    "    capacity = len(s1_records) * max_cands\n",
    "    x_matrix = np.empty((capacity, len(FEATURE_NAMES)), dtype=np.float32)\n",
    "    y_vector = np.empty(capacity, dtype=np.int32)\n",
    "    used = 0\n",
    "    groups, pair_groups = [], []\n",
    "    for sid, name, address, country in s1_records:\n",
    "        cands = blocker.retrieve_candidates_for_record(sid, name, address, country)[:max_cands]\n",
    "        s1_name = normalize_name(name)\n",
    "        s1_address = normalize_address(address)\n",
    "        s1_pin = extract_postal_code(address, country)\n",
    "        s1_numbers = extract_numeric_tokens(address)\n",
    "        group_x, group_y, group_pairs = [], [], []\n",
    "        for cid in cands:\n",
    "            if cid not in cache.norm_names:\n",
    "                continue\n",
    "            group_x.append(compute_pair_features(\n",
    "                \"\", \"\", country, cid, \"\", \"\", cache.countries.get(cid, \"\"),\n",
    "                s1_name, s1_address, s1_pin, s1_numbers,\n",
    "                cache.norm_names[cid], cache.norm_addrs[cid], cache.pins[cid], cache.nums[cid],\n",
    "            ))\n",
    "            group_y.append(1 if cid in gt.get(sid, set()) else 0)\n",
    "            group_pairs.append((sid, cid))\n",
    "        if group_x:\n",
    "            count = len(group_x)\n",
    "            x_matrix[used:used + count] = np.asarray(group_x, dtype=np.float32)\n",
    "            y_vector[used:used + count] = group_y\n",
    "            used += count\n",
    "            groups.append(len(group_x))\n",
    "            if keep_pairs:\n",
    "                pair_groups.append(group_pairs)\n",
    "    return x_matrix[:used], y_vector[:used], groups, pair_groups\n",
    "\n",
    "def evaluate_macro_f05(truth: Dict[str, Set[str]], pred: Dict[str, Set[str]]) -> Tuple[float, float, float]:\n",
    "    \"\"\"Calculate official Macro F0.5, Mean Precision, and Mean Recall metrics.\"\"\"\n",
    "    precisions, recalls, f05s = [], [], []\n",
    "    for sid, t_set in truth.items():\n",
    "        p_set = pred.get(sid, set())\n",
    "        tp = len(t_set & p_set)\n",
    "        fp = len(p_set - t_set)\n",
    "        fn = len(t_set - p_set)\n",
    "        \n",
    "        prec = tp / (tp + fp) if (tp + fp) > 0 else (1.0 if not p_set and not t_set else 0.0)\n",
    "        rec = tp / (tp + fn) if (tp + fn) > 0 else (1.0 if not p_set and not t_set else 0.0)\n",
    "        f05 = (1.25 * prec * rec) / (0.25 * prec + rec) if (0.25 * prec + rec) > 0 else 0.0\n",
    "        \n",
    "        precisions.append(prec)\n",
    "        recalls.append(rec)\n",
    "        f05s.append(f05)\n",
    "        \n",
    "    return float(np.mean(f05s)), float(np.mean(precisions)), float(np.mean(recalls))\n",
    "\n",
    "def predictions_from_scores(pair_groups, scores, threshold):\n",
    "    preds = defaultdict(set)\n",
    "    offset = 0\n",
    "    for group in pair_groups:\n",
    "        for sid, cid in group:\n",
    "            if float(scores[offset]) >= threshold:\n",
    "                preds[sid].add(cid)\n",
    "            offset += 1\n",
    "    return preds\n",
    "\n",
    "def tune_threshold(gt: Dict[str, Set[str]], val_ids: Set[str], pair_groups, scores):\n",
    "    all_scores = np.asarray(scores, dtype=np.float64)\n",
    "    if not len(all_scores):\n",
    "        return float(\"inf\"), 0.0, {}\n",
    "    thresholds = np.unique(np.quantile(all_scores, np.linspace(0.50, 0.999, 100)))\n",
    "    best_threshold, best_f05 = float(thresholds[-1]), -1.0\n",
    "    best_metrics = {}\n",
    "    truth_val = {sid: gt.get(sid, set()) for sid in val_ids}\n",
    "    for threshold in thresholds:\n",
    "        pred = predictions_from_scores(pair_groups, scores, float(threshold))\n",
    "        pred_complete = {sid: pred.get(sid, set()) for sid in val_ids}\n",
    "        f05, precision, recall = evaluate_macro_f05(truth_val, pred_complete)\n",
    "        if f05 > best_f05:\n",
    "            exact_accuracy = sum(pred_complete[sid] == truth_val[sid] for sid in val_ids) / max(len(val_ids), 1)\n",
    "            best_threshold, best_f05 = float(threshold), f05\n",
    "            best_metrics = {\"macro_f0_5\": f05, \"mean_precision\": precision,\n",
    "                            \"mean_recall\": recall, \"exact_set_accuracy\": exact_accuracy}\n",
    "    return best_threshold, best_f05, best_metrics\n",
    "\n",
    "print(\"✅ Rank matrix and threshold tuner ready!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Model Training & Threshold Grid Optimization\n",
    "TRAIN_COHORT_SIZE = 30000   # Set to 0 to train on all source1 records\n",
    "VALIDATION_SIZE = 0.20\n",
    "MAX_CANDIDATES = 100\n",
    "BACKGROUND_CAP = 400000\n",
    "N_ESTIMATORS = 600\n",
    "SEED = 42\n",
    "\n",
    "print(f\"🚀 Starting LightGBM LambdaRank Training...\")\n",
    "full_gt = load_ground_truth_map(DATA_PATHS[\"TRAIN_GROUND_TRUTH\"])\n",
    "all_ids = list(full_gt)\n",
    "\n",
    "if TRAIN_COHORT_SIZE > 0 and TRAIN_COHORT_SIZE < len(all_ids):\n",
    "    rng = random.Random(SEED)\n",
    "    all_ids = rng.sample(all_ids, TRAIN_COHORT_SIZE)\n",
    "\n",
    "train_ids, val_ids_list = train_test_split(all_ids, test_size=VALIDATION_SIZE, random_state=SEED)\n",
    "train_ids, val_ids = set(train_ids), set(val_ids_list)\n",
    "cohort = train_ids | val_ids\n",
    "gt = {sid: full_gt[sid] for sid in cohort}\n",
    "\n",
    "print(f\"📊 S1 Group Splits: Training = {len(train_ids):,} entities | Validation = {len(val_ids):,} entities\")\n",
    "\n",
    "train_s1 = get_s1_records(DATA_PATHS[\"TRAIN_SOURCE1\"], train_ids)\n",
    "val_s1 = get_s1_records(DATA_PATHS[\"TRAIN_SOURCE1\"], val_ids)\n",
    "bg = min(max(len(cohort) * 4, 100_000), BACKGROUND_CAP)\n",
    "candidate_records = collect_training_candidates(cohort, gt, bg)\n",
    "print(f\"📦 Candidate Pool: Indexed {len(candidate_records):,} candidate entities.\")\n",
    "\n",
    "cache = RecordCache(candidate_records)\n",
    "blocker = MultiKeyBlocker(max_candidates_per_s1=MAX_CANDIDATES)\n",
    "blocker.build_candidate_index_from_records(candidate_records, show_progress=True)\n",
    "\n",
    "print(\"⏳ Constructing query-grouped ranking matrices...\")\n",
    "x_train, y_train, group_train, _ = make_rank_matrix(train_s1, cache, blocker, gt, MAX_CANDIDATES)\n",
    "x_val, y_val, group_val, val_pair_groups = make_rank_matrix(\n",
    "    val_s1, cache, blocker, gt, MAX_CANDIDATES, keep_pairs=True\n",
    ")\n",
    "print(f\"📈 Train matrix shape: {x_train.shape} | Val matrix shape: {x_val.shape} | Positive pairs: {int(y_train.sum()):,}\")\n",
    "\n",
    "ranker = LGBMRanker(\n",
    "    objective=\"lambdarank\", metric=\"ndcg\", n_estimators=N_ESTIMATORS,\n",
    "    learning_rate=0.04, num_leaves=31, max_depth=-1, min_child_samples=30,\n",
    "    reg_lambda=2.0, random_state=SEED, n_jobs=-1, verbosity=-1,\n",
    "    label_gain=[0, 3],\n",
    ")\n",
    "\n",
    "print(\"🏋️ Training LGBMRanker model...\")\n",
    "ranker.fit(\n",
    "    x_train, y_train, group=group_train,\n",
    "    eval_set=[(x_val, y_val)], eval_group=[group_val],\n",
    "    callbacks=[early_stopping(40, verbose=False), log_evaluation(50)],\n",
    ")\n",
    "\n",
    "val_scores = ranker.predict(x_val)\n",
    "optimal_threshold, best_f05, metrics = tune_threshold(gt, val_ids, val_pair_groups, val_scores)\n",
    "\n",
    "print(\"\\n⭐ Held-Out Validation Evaluation Results:\")\n",
    "for k, v in metrics.items():\n",
    "    print(f\"  {k:20s}: {v:.4f}\")\n",
    "print(f\"  Optimal Threshold  : {optimal_threshold:.6f}\")\n",
    "\n",
    "# Cleanup training structures from RAM\n",
    "blocker.clear()\n",
    "cache.clear()\n",
    "del x_train, y_train, x_val, y_val, candidate_records\n",
    "gc.collect()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Streaming Country-Partitioned Test Inference & TSV File Generation\n",
    "def make_test_features(record: Record, cands: List[str], cache: RecordCache):\n",
    "    _, name, address, country = record\n",
    "    n, a = normalize_name(name), normalize_address(address)\n",
    "    pin, nums = extract_postal_code(address, country), extract_numeric_tokens(address)\n",
    "    ids, vectors = [], []\n",
    "    for cid in cands:\n",
    "        if cid in cache.norm_names:\n",
    "            ids.append(cid)\n",
    "            vectors.append(compute_pair_features(\n",
    "                \"\", \"\", country, cid, \"\", \"\", cache.countries.get(cid, \"\"),\n",
    "                n, a, pin, nums, cache.norm_names[cid], cache.norm_addrs[cid],\n",
    "                cache.pins[cid], cache.nums[cid],\n",
    "            ))\n",
    "    return ids, np.asarray(vectors, dtype=np.float32) if vectors else np.empty((0, len(FEATURE_NAMES)), np.float32)\n",
    "\n",
    "def run_test_inference(ranker, threshold: float, max_candidates: int = 100):\n",
    "    print(f\"\\n🔮 Streaming Test Candidate Scoring & Inference (Max Cands={max_candidates})...\")\n",
    "    s1_by_country = defaultdict(list)\n",
    "    for rec in read_source(DATA_PATHS[\"TEST_SOURCE1\"]):\n",
    "        s1_by_country[normalize_country(rec[3])].append(rec)\n",
    "        \n",
    "    with MATCHING_RESULTS_PATH.open(\"w\", encoding=\"utf-8\", newline=\"\") as fm, \\\n",
    "         CANDIDATE_PAIRS_PATH.open(\"w\", encoding=\"utf-8\", newline=\"\") as fc:\n",
    "        wm = csv.writer(fm, delimiter=\"\\t\", lineterminator=\"\\n\")\n",
    "        wc = csv.writer(fc, delimiter=\"\\t\", lineterminator=\"\\n\")\n",
    "        \n",
    "        wm.writerow((\"source1_entity_id\", \"matched_entity_ids\"))\n",
    "        wc.writerow((\"source1_entity_id\", \"candidate_entity_ids\"))\n",
    "        \n",
    "        for country, source1 in s1_by_country.items():\n",
    "            print(f\"🌍 Processing {country} partition ({len(source1):,} S1 queries)...\")\n",
    "            candidate_records = []\n",
    "            for path in (DATA_PATHS[\"TEST_SOURCE2\"], DATA_PATHS[\"TEST_SOURCE3\"]):\n",
    "                candidate_records.extend(rec for rec in read_source(path) if normalize_country(rec[3]) == country)\n",
    "                \n",
    "            cache = RecordCache(candidate_records)\n",
    "            blocker = MultiKeyBlocker(max_candidates_per_s1=max_candidates)\n",
    "            blocker.build_candidate_index_from_records(candidate_records, show_progress=False)\n",
    "            \n",
    "            for rec in tqdm(source1, desc=f\"Scoring {country}\"):\n",
    "                cands = blocker.retrieve_candidates_for_record(rec[0], rec[1], rec[2], rec[3])[:max_candidates]\n",
    "                ids, matrix = make_test_features(rec, cands, cache)\n",
    "                chosen = []\n",
    "                if len(ids):\n",
    "                    scores = ranker.predict(matrix)\n",
    "                    chosen = [cid for cid, score in zip(ids, scores) if score >= threshold]\n",
    "                    \n",
    "                wm.writerow((rec[0], \",\".join(chosen)))\n",
    "                wc.writerow((rec[0], \",\".join(cands)))\n",
    "                \n",
    "            blocker.clear()\n",
    "            cache.clear()\n",
    "            del candidate_records, blocker, cache\n",
    "            gc.collect()\n",
    "            \n",
    "    print(f\"\\n🎉 Successfully generated output files:\")\n",
    "    print(f\"  1. {MATCHING_RESULTS_PATH}\")\n",
    "    print(f\"  2. {CANDIDATE_PAIRS_PATH}\")\n",
    "\n",
    "run_test_inference(ranker, optimal_threshold, max_candidates=MAX_CANDIDATES)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# File Integrity & Output Preview Verification\n",
    "def verify_outputs():\n",
    "    print(\"🔍 Output Verification Summary:\")\n",
    "    for label, path in [(\"Matching Results\", MATCHING_RESULTS_PATH), (\"Candidate Pairs\", CANDIDATE_PAIRS_PATH)]:\n",
    "        if not path.exists():\n",
    "            print(f\"  ❌ {label} not found at {path}\")\n",
    "            continue\n",
    "        size_mb = path.stat().st_size / (1024 * 1024)\n",
    "        with path.open(\"r\", encoding=\"utf-8\") as f:\n",
    "            lines = [f.readline() for _ in range(6)]\n",
    "            f.seek(0)\n",
    "            line_count = sum(1 for _ in f)\n",
    "        print(f\"  ✅ {label} ({path.name}): {line_count:,} total lines, {size_mb:.2f} MB\")\n",
    "        print(f\"     Header: {lines[0].strip()}\")\n",
    "        print(\"     Sample rows:\")\n",
    "        for line in lines[1:6]:\n",
    "            print(f\"       {line.strip()}\")\n",
    "        print(\"-\" * 60)\n",
    "\n",
    "verify_outputs()\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

output_path = Path(r"c:\Users\A\Downloads\amazon_ml_challenge_2026\code_1\kaggle_business_entity_resolution.ipynb")
with output_path.open("w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print(f"Successfully updated notebook at {output_path}")
